#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CorpTrainingManager.Droid.Resource", IsApplication=true)]

namespace CorpTrainingManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backword = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int customer_progress = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int customer_progress_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int login_button_bg_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int navigation_left = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sidebar_background = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int btn_start = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int catalog = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int country_lvcountry = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int filter_edit = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fl_content = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int ib_exit = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int iv_titlepicture = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int ll_content = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int ll_load = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ll_root = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int lv_result = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int pb_pull_list_header = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int title = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int tv_maintitle = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int tv_pull_list_header_title = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int tv_scores = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int tv_title = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int acivity_user = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_result = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int item_userresults = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int item_users = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int emotionstore_progresscancelbtn = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int icon_exit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int landingscape = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int login_button_nor = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int login_button_press = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login_input = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int mainicon = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int search_bar_icon_normal = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int show_head_toast_bg = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int title_red_bg = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int video_default_icon = 2130903051;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
